[features]
seeds = false
[programs.devnet]
nft_marketplace = "6LGmFHpmFmBdv2UnsopN8A4qdAcBrniiikoZjpJ8ti5S"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/mfa13/.config/solana/nft_marketplace.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
app = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/**/*.ts"
